info:
  app:
    name: @project.name@
    version: @project.version@

spring:
  application:
    name: player-service

server:
  port: 8091

---

profiles: test

eureka:
  client:
    enabled: false

